/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.InsertController;
import Controller.SearchController;
import Controller.UpdateController;

/**
 *
 * @author chath
 */
public class AddLibrarian extends javax.swing.JFrame {

    /**
     * Creates new form AddPatrons
     */
    public AddLibrarian() {
        initComponents();
        new DataController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patronIdTF3 = new javax.swing.JTextField();
        patronIdLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        passwordTF = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        privilegeCB = new javax.swing.JComboBox<>();
        privilegeLabel = new javax.swing.JLabel();
        hourlyRateTF = new javax.swing.JTextField();
        hourlyRateLabel = new javax.swing.JLabel();
        genderCB = new javax.swing.JComboBox<>();
        genderLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        nicTF = new javax.swing.JTextField();
        fullNameTF = new javax.swing.JTextField();
        fullNameLabel = new javax.swing.JLabel();
        usernameStatusTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        patronIdTF3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patronIdTF3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        patronIdLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patronIdLabel3.setText("Patron ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 15, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 15, -1, -1));

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel.setText("Add Librarian");
        jPanel1.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addBtnSmall.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, -1, -1));

        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clearBtn.png"))); // NOI18N
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 241, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setText("Password:");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameLabel.setText("Username:");
        jPanel1.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        usernameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTFKeyReleased(evt);
            }
        });
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 241, -1));

        privilegeCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        privilegeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Admin" }));
        privilegeCB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(privilegeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 136, -1));

        privilegeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        privilegeLabel.setText("Privilege:");
        jPanel1.add(privilegeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        hourlyRateTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hourlyRateTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(hourlyRateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 241, -1));

        hourlyRateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hourlyRateLabel.setText("Hourly Rate:");
        jPanel1.add(hourlyRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        genderCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(genderCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 136, -1));

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderLabel.setText("Gender:");
        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        telephoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telephoneLabel.setText("Telephone:");
        jPanel1.add(telephoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        telephoneTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telephoneTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(telephoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 241, -1));

        addressTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addressTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(addressTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 241, -1));

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addressLabel.setText("Address: ");
        jPanel1.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        nicLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nicLabel.setText("NIC Number:");
        jPanel1.add(nicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        nicTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nicTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(nicTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 241, -1));

        fullNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fullNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(fullNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 241, -1));

        fullNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fullNameLabel.setText("Fullname: ");
        jPanel1.add(fullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        usernameStatusTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameStatusTF.setBorder(null);
        usernameStatusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameStatusTFActionPerformed(evt);
            }
        });
        jPanel1.add(usernameStatusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 241, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addBackground.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        new UpdateController().addLibrarianClear(fullNameTF, nicTF, addressTF, telephoneTF, genderCB, hourlyRateTF, privilegeCB, usernameTF, passwordTF);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        InsertController insertController = new InsertController();
        insertController.insertLibrarian(fullNameTF.getText(), nicTF.getText(), addressTF.getText(), telephoneTF.getText(), Double.parseDouble(hourlyRateTF.getText()), 
                (String)genderCB.getSelectedItem(), usernameTF.getText(), passwordTF.getText(), (String)privilegeCB.getSelectedItem());
    }//GEN-LAST:event_addBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new AdminMenu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void usernameTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTFKeyReleased
        // TODO add your handling code here:
        new SearchController().searchAddingDropDown("Username", usernameTF, usernameStatusTF);
    }//GEN-LAST:event_usernameTFKeyReleased

    private void usernameStatusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameStatusTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameStatusTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLibrarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hourlyRateLabel;
    private javax.swing.JTextField hourlyRateTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JTextField nicTF;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel patronIdLabel3;
    private javax.swing.JTextField patronIdTF3;
    private javax.swing.JComboBox<String> privilegeCB;
    private javax.swing.JLabel privilegeLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTF;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameStatusTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
