/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.LoginController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chath
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        new DataController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passWordLabel = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        passWordPF = new javax.swing.JPasswordField();
        forgotPassLabel = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        loginAsLibrarianLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 15, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 15, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userNameLabel.setText("Username:");
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        passWordLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        passWordLabel.setText("Password:");
        jPanel1.add(passWordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        topicLabel.setFont(new java.awt.Font("Palatino Linotype", 1, 40)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 153, 255));
        topicLabel.setText("Admin Login");
        jPanel1.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        userNameTF.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        userNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 289, 33));

        passWordPF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        passWordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordPFActionPerformed(evt);
            }
        });
        jPanel1.add(passWordPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 289, 35));

        forgotPassLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgotPassLabel.setText("Forgot Password?");
        forgotPassLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassLabelMouseClicked(evt);
            }
        });
        jPanel1.add(forgotPassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        loginBtn.setBackground(new java.awt.Color(0, 204, 0));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setOpaque(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 41));

        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 99, 41));

        loginAsLibrarianLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginAsLibrarianLabel.setText("Login As Librarian");
        loginAsLibrarianLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginAsLibrarianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAsLibrarianLabelMouseClicked(evt);
            }
        });
        jPanel1.add(loginAsLibrarianLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminLoginBackground.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void passWordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordPFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        new LoginController().AdminLogin(userNameTF, passWordPF, this);
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void loginAsLibrarianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginAsLibrarianLabelMouseClicked
        // TODO add your handling code here:
        new LibrarianLogin().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_loginAsLibrarianLabelMouseClicked

    private void forgotPassLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassLabelMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(new JFrame(), "Contact administrator!");
    }//GEN-LAST:event_forgotPassLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel forgotPassLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginAsLibrarianLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel passWordLabel;
    private javax.swing.JPasswordField passWordPF;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}
