/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.UpdateController;

/**
 *
 * @author chath
 */
public class UpdateBook extends javax.swing.JFrame {
    
    static int totalNoOfBooks, availableBooks;
    
    /**
     * Creates new form UpdateBook
     */
    public UpdateBook() {
        initComponents();
        new DataController().setIcon(this);
    }
    
   
    public void getVariabesFromUpdate(String totNoOfBooks, String avaBooks){
        totalNoOfBooks = Integer.parseInt(totNoOfBooks);
        availableBooks = Integer.parseInt(avaBooks);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        noOfCopiesLabel = new javax.swing.JLabel();
        noOfCopiesTF = new javax.swing.JTextField();
        issuedYearTF = new javax.swing.JTextField();
        issuedYearLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        genreCB = new javax.swing.JComboBox<>();
        authorTF = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        editionLabel = new javax.swing.JLabel();
        editionTF = new javax.swing.JTextField();
        bookNameTF = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        isbnLabel = new javax.swing.JLabel();
        isbnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 15, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 15, -1, -1));

        noOfCopiesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noOfCopiesLabel.setText("No of Copies:");
        jPanel1.add(noOfCopiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        noOfCopiesTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noOfCopiesTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(noOfCopiesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 241, -1));

        issuedYearTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        issuedYearTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(issuedYearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 241, -1));

        issuedYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issuedYearLabel.setText("Issued Year:");
        jPanel1.add(issuedYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        genreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genreLabel.setText("Genre: ");
        jPanel1.add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        genreCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Fantasy", "Sceince Fiction", "Mystery", "Romance", "Horror", "Crime", "Historical Fiction", "Distopian" }));
        genreCB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(genreCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 136, -1));

        authorTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        authorTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(authorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 241, -1));

        authorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authorLabel.setText("Author:");
        jPanel1.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        editionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editionLabel.setText("Edition:");
        jPanel1.add(editionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        editionTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editionTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(editionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 241, -1));

        bookNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(bookNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 241, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Name:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel.setText("Update Book");
        jPanel1.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 64, -1, -1));

        UpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updateBtnSmall.png"))); // NOI18N
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        isbnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnLabel.setText("ISBN:");
        jPanel1.add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        isbnTF.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        isbnTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(isbnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 241, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/updateBackground.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        new UpdateController().updateBook(isbnTF.getText(), bookNameTF.getText(), editionTF.getText(), authorTF.getText(), 
                (String)genreCB.getSelectedItem(), Integer.parseInt(noOfCopiesTF.getText()), availableBooks, totalNoOfBooks, Integer.parseInt(issuedYearTF.getText()), this);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new ViewAllBooks().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel authorLabel;
    public javax.swing.JTextField authorTF;
    private javax.swing.JButton backBtn;
    public javax.swing.JTextField bookNameTF;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel editionLabel;
    public javax.swing.JTextField editionTF;
    public javax.swing.JComboBox<String> genreCB;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel isbnLabel;
    public javax.swing.JTextField isbnTF;
    private javax.swing.JLabel issuedYearLabel;
    public javax.swing.JTextField issuedYearTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noOfCopiesLabel;
    public javax.swing.JTextField noOfCopiesTF;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
