/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.InsertController;
import Controller.UpdateController;

/**
 *
 * @author chath
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBooks() {
        initComponents();
        new DataController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        topicLabel = new javax.swing.JLabel();
        editionTF = new javax.swing.JTextField();
        editionLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();
        genreLabel = new javax.swing.JLabel();
        issuedYearLabel = new javax.swing.JLabel();
        issuedYearTF = new javax.swing.JTextField();
        genreCB = new javax.swing.JComboBox<>();
        noOfCopiesLabel = new javax.swing.JLabel();
        noOfCopiesTF = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        ISBNLabel = new javax.swing.JLabel();
        ISBNTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 15, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 15, -1, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Name:");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        nameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 241, -1));

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel.setText("Add Book");
        jPanel1.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        editionTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(editionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 241, -1));

        editionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editionLabel.setText("Edition:");
        jPanel1.add(editionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        authorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authorLabel.setText("Author:");
        jPanel1.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        authorTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(authorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 241, -1));

        genreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genreLabel.setText("Genre: ");
        jPanel1.add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        issuedYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issuedYearLabel.setText("Issued Year:");
        jPanel1.add(issuedYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        issuedYearTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(issuedYearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 241, -1));

        genreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Fantasy", "Sceince Fiction", "Mystery", "Romance", "Horror", "Crime", "Historical Fiction", "Distopian" }));
        genreCB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(genreCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 136, -1));

        noOfCopiesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noOfCopiesLabel.setText("No of Copies:");
        jPanel1.add(noOfCopiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        noOfCopiesTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(noOfCopiesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 241, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        clearBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clearBtn.png"))); // NOI18N
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addBtnSmall.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        ISBNLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ISBNLabel.setText("ISBN:");
        jPanel1.add(ISBNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        ISBNTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(ISBNTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 241, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addBookBackground.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new LibrarianMenu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        new UpdateController().addBookClear(ISBNTF, nameTF, editionTF, authorTF, genreCB, noOfCopiesTF, issuedYearTF);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        new InsertController().insertBook(ISBNTF.getText(), nameTF.getText(), editionTF.getText(), authorTF.getText(), (String)genreCB.getSelectedItem(), Integer.parseInt(noOfCopiesTF.getText()),Integer.parseInt(noOfCopiesTF.getText()), Integer.parseInt(issuedYearTF.getText()));
        new UpdateController().addBookClear(ISBNTF, nameTF, editionTF, authorTF, genreCB, noOfCopiesTF, issuedYearTF);
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISBNLabel;
    private javax.swing.JTextField ISBNTF;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel editionLabel;
    private javax.swing.JTextField editionTF;
    private javax.swing.JComboBox<String> genreCB;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel issuedYearLabel;
    private javax.swing.JTextField issuedYearTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel noOfCopiesLabel;
    private javax.swing.JTextField noOfCopiesTF;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
