/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;
import Controller.DeleteController;
import Controller.InsertController;
import Controller.SearchController;
import Controller.UpdateController;

/**
 *
 * @author chath
 */
public class LendBook extends javax.swing.JFrame {

    /**
     * Creates new form LendBook
     */
    public LendBook() {
        initComponents();
        new DataController().setIcon(this);
        new UpdateController().updateDateFromLendConstructor(lendDateDC, dueDateTF, Integer.parseInt((String)borrowePeriodCB.getSelectedItem()));
        new UpdateController().updateAllFines();
        new UpdateController().updateLendTable(lendsTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        patronSearchCB = new javax.swing.JComboBox<>();
        patronIdLabel = new javax.swing.JLabel();
        patronIdTF = new javax.swing.JTextField();
        patronNameTF = new javax.swing.JTextField();
        patronNameLabel = new javax.swing.JLabel();
        bookNameTF = new javax.swing.JTextField();
        isbnLabel2 = new javax.swing.JLabel();
        isbnSearchCB = new javax.swing.JComboBox<>();
        isbnTF = new javax.swing.JTextField();
        isbnLabel = new javax.swing.JLabel();
        lendDateLabel = new javax.swing.JLabel();
        lendDateDC = new com.toedter.calendar.JDateChooser();
        borrowePeriodCB = new javax.swing.JComboBox<>();
        borrowedPeriodLabel = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        lendBtn = new javax.swing.JButton();
        dueDateTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lendsTable = new javax.swing.JTable();
        searchByLabel = new javax.swing.JLabel();
        searchByCB = new javax.swing.JComboBox<>();
        searchTF = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        topicLabel2 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jTabbedPane.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneMouseClicked(evt);
            }
        });
        jTabbedPane.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPanePropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 13, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 13, -1, -1));

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel.setText("Lend Book");
        jPanel1.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 13, -1, -1));

        patronSearchCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patronSearchCB.setBorder(null);
        patronSearchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patronSearchCBActionPerformed(evt);
            }
        });
        jPanel1.add(patronSearchCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 130, -1));

        patronIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patronIdLabel.setText("Patron ID:");
        jPanel1.add(patronIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        patronIdTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patronIdTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        patronIdTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patronIdTFKeyReleased(evt);
            }
        });
        jPanel1.add(patronIdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 130, -1));

        patronNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patronNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(patronNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 190, -1));

        patronNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        patronNameLabel.setText("Patron Name:");
        jPanel1.add(patronNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        bookNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.add(bookNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 190, -1));

        isbnLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnLabel2.setText("Book Name:");
        jPanel1.add(isbnLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        isbnSearchCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isbnSearchCB.setBorder(null);
        isbnSearchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnSearchCBActionPerformed(evt);
            }
        });
        jPanel1.add(isbnSearchCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 130, -1));

        isbnTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isbnTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        isbnTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isbnTFKeyReleased(evt);
            }
        });
        jPanel1.add(isbnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, -1));

        isbnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnLabel.setText("Book ISBN:");
        jPanel1.add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        lendDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lendDateLabel.setText("Lend Date:");
        jPanel1.add(lendDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lendDateDC.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lendDateDCPropertyChange(evt);
            }
        });
        jPanel1.add(lendDateDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 130, -1));

        borrowePeriodCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "14", "21", "28" }));
        borrowePeriodCB.setBorder(null);
        borrowePeriodCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowePeriodCBActionPerformed(evt);
            }
        });
        jPanel1.add(borrowePeriodCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 114, -1));

        borrowedPeriodLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        borrowedPeriodLabel.setText("Brrowing Period:");
        jPanel1.add(borrowedPeriodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        dueDateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dueDateLabel.setText("Due Date:");
        jPanel1.add(dueDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));

        lendBtn.setBackground(new java.awt.Color(255, 255, 255));
        lendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lendBtnSmall.png"))); // NOI18N
        lendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));
        jPanel1.add(dueDateTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lendBookBackground.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane.addTab("Lend Books", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lendsTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lendsTable.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lendsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lend ID", "Patron ID", "ISBN", "Lended Date", "Due Date", "Fine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lendsTable);
        if (lendsTable.getColumnModel().getColumnCount() > 0) {
            lendsTable.getColumnModel().getColumn(0).setResizable(false);
            lendsTable.getColumnModel().getColumn(1).setResizable(false);
            lendsTable.getColumnModel().getColumn(2).setResizable(false);
            lendsTable.getColumnModel().getColumn(3).setResizable(false);
            lendsTable.getColumnModel().getColumn(4).setResizable(false);
            lendsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        searchByLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        searchByLabel.setText("Search by:");

        searchByCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lend ID", "Patron ID", "ISBN" }));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        searchBtn.setContentAreaFilled(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        refreshBtn.setContentAreaFilled(false);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn1.setContentAreaFilled(false);
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        topicLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel2.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel2.setText("Return Books");

        returnBtn.setBackground(new java.awt.Color(255, 255, 255));
        returnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/return.png"))); // NOI18N
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(topicLabel2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(316, 316, 316)
                            .addComponent(searchByLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchByCB, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(topicLabel2)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchByLabel)
                            .addComponent(searchByCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(returnBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane.addTab("Return Books", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(LibrarianLogin.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new LibrarianMenu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void patronSearchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patronSearchCBActionPerformed
        // TODO add your handling code here:
        new SearchController().findNameBySelection("patronId", patronSearchCB, patronNameTF, patronIdTF);
        
    }//GEN-LAST:event_patronSearchCBActionPerformed

    private void patronIdTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patronIdTFKeyReleased
        // TODO add your handling code here:
        new SearchController().searchDropDown("patronId", patronIdTF, patronSearchCB);
    }//GEN-LAST:event_patronIdTFKeyReleased

    private void isbnTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnTFKeyReleased
        // TODO add your handling code here:
        new SearchController().searchDropDown("ISBN", isbnTF, isbnSearchCB);
    }//GEN-LAST:event_isbnTFKeyReleased

    private void isbnSearchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnSearchCBActionPerformed
        // TODO add your handling code here:
        new SearchController().findNameBySelection("ISBN", isbnSearchCB, bookNameTF, isbnTF);
    }//GEN-LAST:event_isbnSearchCBActionPerformed

    private void lendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendBtnActionPerformed
        // TODO add your handling code here:
        new InsertController().lendBook(patronSearchCB, isbnSearchCB, lendDateDC, dueDateTF);
    }//GEN-LAST:event_lendBtnActionPerformed

    private void lendDateDCPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lendDateDCPropertyChange
        // TODO add your handling code here:
        new UpdateController().updateDateInLend(lendDateDC, dueDateTF, Integer.parseInt((String)borrowePeriodCB.getSelectedItem()));
    }//GEN-LAST:event_lendDateDCPropertyChange

    private void borrowePeriodCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowePeriodCBActionPerformed
        // TODO add your handling code here:
        new UpdateController().updateDateInLend(lendDateDC, dueDateTF, Integer.parseInt((String)borrowePeriodCB.getSelectedItem()));
    }//GEN-LAST:event_borrowePeriodCBActionPerformed

    
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        new SearchController().searchLend(searchByCB, searchTF, lendsTable);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        searchTF.setText("");
        searchByCB.setSelectedIndex(0);
        new UpdateController().updateLendTable(lendsTable);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        new LibrarianMenu().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        new DeleteController().returnBook(lendsTable);
        new UpdateController().updateLendTable(lendsTable);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void jTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneMouseClicked
        // TODO add your handling code here:
        new UpdateController().updateLendTable(lendsTable);
    }//GEN-LAST:event_jTabbedPaneMouseClicked

    private void jTabbedPanePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPanePropertyChange
        // TODO add your handling code here:
        new UpdateController().updateLendTable(lendsTable);
    }//GEN-LAST:event_jTabbedPanePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LendBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LendBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    public javax.swing.JTextField bookNameTF;
    private javax.swing.JComboBox<String> borrowePeriodCB;
    private javax.swing.JLabel borrowedPeriodLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JTextField dueDateTF;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JLabel isbnLabel2;
    public javax.swing.JComboBox<String> isbnSearchCB;
    public javax.swing.JTextField isbnTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton lendBtn;
    private com.toedter.calendar.JDateChooser lendDateDC;
    private javax.swing.JLabel lendDateLabel;
    public static javax.swing.JTable lendsTable;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel patronIdLabel;
    public javax.swing.JTextField patronIdTF;
    private javax.swing.JLabel patronNameLabel;
    public javax.swing.JTextField patronNameTF;
    public javax.swing.JComboBox<String> patronSearchCB;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> searchByCB;
    private javax.swing.JLabel searchByLabel;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel topicLabel;
    private javax.swing.JLabel topicLabel2;
    // End of variables declaration//GEN-END:variables
}
