/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;

/**
 *
 * @author chath
 */
public class LibrarianMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public LibrarianMenu() {
        initComponents();
        new DataController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addBooksBtn = new javax.swing.JButton();
        lendBooksBtn = new javax.swing.JButton();
        viewUsersBtn = new javax.swing.JButton();
        addUsersBtn = new javax.swing.JButton();
        viewBooksBtn = new javax.swing.JButton();
        welcomeTL = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 15, -1, -1));

        minimizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });
        jPanel1.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Librarian Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        addBooksBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddBooks.png"))); // NOI18N
        addBooksBtn.setBorder(null);
        addBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 157, -1, -1));

        lendBooksBtn.setBackground(new java.awt.Color(255, 255, 255));
        lendBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LendBooks.png"))); // NOI18N
        lendBooksBtn.setBorder(null);
        lendBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendBooksBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lendBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 157, -1, -1));

        viewUsersBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewUsersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ViewPatrons.png"))); // NOI18N
        viewUsersBtn.setBorder(null);
        viewUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 354, -1, -1));

        addUsersBtn.setBackground(new java.awt.Color(255, 255, 255));
        addUsersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddPatrons.png"))); // NOI18N
        addUsersBtn.setAlignmentX(0.5F);
        addUsersBtn.setBorder(null);
        addUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsersBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addUsersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 157, -1, -1));

        viewBooksBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ViewBooks.png"))); // NOI18N
        viewBooksBtn.setBorder(null);
        viewBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBooksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 354, -1, -1));

        welcomeTL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        welcomeTL.setForeground(new java.awt.Color(102, 102, 102));
        welcomeTL.setText("Welcome, Chathura!");
        jPanel1.add(welcomeTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 40));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 467, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void addUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsersBtnActionPerformed
        // TODO add your handling code here:
        new AddPatrons().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_addUsersBtnActionPerformed

    private void addBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBooksBtnActionPerformed
        // TODO add your handling code here:
        new AddBooks().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_addBooksBtnActionPerformed

    private void lendBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendBooksBtnActionPerformed
        // TODO add your handling code here:
        new LendBook().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_lendBooksBtnActionPerformed

    private void viewUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersBtnActionPerformed
        // TODO add your handling code here:
        new ViewAllPatrons().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_viewUsersBtnActionPerformed

    private void viewBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksBtnActionPerformed
        // TODO add your handling code here:
        new ViewAllBooks().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_viewBooksBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        new LibrarianLogin().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBooksBtn;
    private javax.swing.JButton addUsersBtn;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lendBooksBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JButton viewBooksBtn;
    private javax.swing.JButton viewUsersBtn;
    public javax.swing.JLabel welcomeTL;
    // End of variables declaration//GEN-END:variables
}
