/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DataController;

/**
 *
 * @author chath
 */
public class ViewBook extends javax.swing.JFrame {

    /**
     * Creates new form ViewBook
     */
    public ViewBook() {
        initComponents();
        new DataController().setIcon(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        closeLabel1 = new javax.swing.JLabel();
        minimizeLabel1 = new javax.swing.JLabel();
        noOfCopiesLabel = new javax.swing.JLabel();
        noOfCopiesTF = new javax.swing.JTextField();
        issuedYearTF = new javax.swing.JTextField();
        issuedYearLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        genreCB = new javax.swing.JComboBox<>();
        authorTF = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        editionLabel = new javax.swing.JLabel();
        editionTF = new javax.swing.JTextField();
        bookNameTF = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        topicLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        isbnLabel = new javax.swing.JLabel();
        isbnTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 550));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        closeLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(closeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 15, -1, -1));

        minimizeLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        minimizeLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(minimizeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 15, -1, -1));

        noOfCopiesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noOfCopiesLabel.setText("No of Copies:");
        jPanel2.add(noOfCopiesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        noOfCopiesTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noOfCopiesTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(noOfCopiesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 241, -1));

        issuedYearTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        issuedYearTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(issuedYearTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 241, -1));

        issuedYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        issuedYearLabel.setText("Issued Year:");
        jPanel2.add(issuedYearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        genreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genreLabel.setText("Genre: ");
        jPanel2.add(genreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        genreCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Fantasy", "Sceince Fiction", "Mystery", "Romance", "Horror", "Crime", "Historical Fiction", "Distopian" }));
        genreCB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(genreCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 136, -1));

        authorTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        authorTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(authorTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 241, -1));

        authorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        authorLabel.setText("Author:");
        jPanel2.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        editionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editionLabel.setText("Edition:");
        jPanel2.add(editionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        editionTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editionTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(editionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 241, -1));

        bookNameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookNameTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(bookNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 241, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Name:");
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        topicLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(0, 51, 255));
        topicLabel.setText("View Book");
        jPanel2.add(topicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        isbnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        isbnLabel.setText("ISBN:");
        jPanel2.add(isbnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        isbnTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isbnTF.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.add(isbnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 241, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/viewBackground.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new ViewAllBooks().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void minimizeLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabel1MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(AddBooks.ICONIFIED);
    }//GEN-LAST:event_minimizeLabel1MouseClicked

    private void closeLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_closeLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel;
    public javax.swing.JTextField authorTF;
    private javax.swing.JButton backBtn;
    public javax.swing.JTextField bookNameTF;
    private javax.swing.JLabel closeLabel1;
    private javax.swing.JLabel editionLabel;
    public javax.swing.JTextField editionTF;
    public javax.swing.JComboBox<String> genreCB;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel isbnLabel;
    public javax.swing.JTextField isbnTF;
    private javax.swing.JLabel issuedYearLabel;
    public javax.swing.JTextField issuedYearTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimizeLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noOfCopiesLabel;
    public javax.swing.JTextField noOfCopiesTF;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
